### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by brainstorm** [KunihikoKido/atom-elasticsearch-client#1]
[Enter steps to reproduce below:]
1. Ctrl+Alt+s

**Atom Version**: 0.208.0
**System**: Mac OS X 10.10.1
**Thrown From**: [elasticsearch-client](https://github.com/KunihikoKido/atom-elasticsearch-client) package, v0.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getText' of undefined

```
At /Users/romanvg/.atom/packages/elasticsearch-client/lib/elasticsearch-client.coffee:56

TypeError: Cannot read property 'getText' of undefined
    at Object.module.exports.getText (/Users/romanvg/.atom/packages/elasticsearch-client/lib/elasticsearch-client.coffee:291:27)
    at Object.module.exports.POST (/Users/romanvg/.atom/packages/elasticsearch-client/lib/elasticsearch-client.coffee:378:20)
    at atom-workspace.<anonymous> (/Users/romanvg/.atom/packages/elasticsearch-client/lib/elasticsearch-client.coffee:265:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```
### Commands

```
  3x -0:00.5.0 elasticsearch-client:search-request-body-search (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
elasticsearch-client, v0.1.0
language-groovy, v0.4.0
wakatime, v4.0.9

# Dev
No dev packages
```

**Comment by KunihikoKido** [comment]
Hi @brainstorm 

Thank you for feedback.
Few bugs to be fixed in v0.2.2. please try again.
