### ISSUE TITLE
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script

### ISSUE THREAD

**Issue by n1k0** [KunihikoKido/atom-elasticsearch-client#15]
Trying to perform a request on this simple query:

```json
{
  "query": {
    "match_all": {}
  }
}
```

Complete error message:

> EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

Stack:

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at Function (<anonymous>)
    at /home/niko/.atom/packages/floobits/node_modules/lodash/lodash.js:14843:16
    at apply (/home/niko/.atom/packages/floobits/node_modules/lodash/lodash.js:494:27)
    at /home/niko/.atom/packages/floobits/node_modules/lodash/lodash.js:15227:16
    at apply (/home/niko/.atom/packages/floobits/node_modules/lodash/lodash.js:496:27)
    at /home/niko/.atom/packages/floobits/node_modules/lodash/lodash.js:6600:16
    at Object.template (/home/niko/.atom/packages/floobits/node_modules/lodash/lodash.js:14842:20)
    at resolveUrl (/home/niko/.atom/packages/elasticsearch-client/node_modules/elasticsearch/src/lib/client_action.js:233:22)
    at exec (/home/niko/.atom/packages/elasticsearch-client/node_modules/elasticsearch/src/lib/client_action.js:282:26)
    at EsApiClient.action (/home/niko/.atom/packages/elasticsearch-client/node_modules/elasticsearch/src/lib/client_action.js:61:16)
    at SearchRequestBody.module.exports.SearchRequestBody.run (/home/niko/.atom/packages/elasticsearch-client/lib/commands/search-request-body.coffee:15:13)
    at SearchRequestBody.BaseCommand.initialize (/home/niko/.atom/packages/elasticsearch-client/lib/commands/base.coffee:31:7)
    at SearchRequestBody.BaseCommand (/home/niko/.atom/packages/elasticsearch-client/lib/commands/base.coffee:27:6)
    at new SearchRequestBody (/home/niko/.atom/packages/elasticsearch-client/lib/commands/search-request-body.coffee:4:7)
    at /home/niko/.atom/packages/elasticsearch-client/lib/elasticsearch-client.coffee:386:66
    at HTMLElement.<anonymous> (/home/niko/.atom/packages/elasticsearch-client/lib/elasticsearch-client.coffee:246:7)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

Atom version: 1.19

OS: Fedora 26

**Comment by n1k0** [comment]
Duplicate of #4.
