### ISSUE TITLE
Failed to activate the elasticsearch-client package

### ISSUE THREAD

**Issue by gendalf** [KunihikoKido/atom-elasticsearch-client#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11
**Thrown From**: [elasticsearch-client](https://github.com/KunihikoKido/atom-elasticsearch-client) package, v0.9.1
### Stack Trace

Failed to activate the elasticsearch-client package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function (native)
    at denodeifyWithoutCount (/Users/FelixBerth/.atom/packages/elasticsearch-client/node_modules/promise/lib/node-extensions.js:90:10)
    at Function.Promise.denodeify (/Users/FelixBerth/.atom/packages/elasticsearch-client/node_modules/promise/lib/node-extensions.js:19:12)
    at Object.<anonymous> (/Users/FelixBerth/.atom/packages/elasticsearch-client/lib/commands/helper-load-index-data.coffee:11:20)
    at Object.<anonymous> (/Users/FelixBerth/.atom/packages/elasticsearch-client/lib/commands/helper-load-index-data.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/FelixBerth/.atom/packages/elasticsearch-client/lib/elasticsearch-client.coffee:130:30)
    at Object.<anonymous> (/Users/FelixBerth/.atom/packages/elasticsearch-client/lib/elasticsearch-client.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:721:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:801:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -6:15 core:undo (atom-text-editor.editor.mini.is-focused)
     -6:11.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -6:11.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -6:03.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -6:02.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -4:57.8.0 core:copy (div.package-readme.native-key-bindings)
     -0:45 fuzzy-finder:toggle-file-finder (div.package-detail.panels-item)
     -0:42.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:42.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:41 fuzzy-finder:toggle-file-finder (div.package-detail.panels-item)
     -0:35.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:35.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:31.3.0 command-palette:toggle (div.package-detail.panels-item)
  3x -0:27.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:05.9.0 command-palette:toggle (div.package-detail.panels-item)
     -0:01.9.0 elasticsearch:settings-switch-server (div.package-detail.panels-item)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-vue-component"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
SFTP-deployment, v1.0.2
Stylus, v1.2.1
atom-jade, v0.3.0
elasticsearch-client, v0.9.1
language-vue, v0.8.0
linter, v1.11.3
linter-coffeescript, v1.0.0
linter-eslint, v5.2.7
remote-sync, v3.5.0

# Dev
No dev packages
```

**Comment by KunihikoKido** [comment]
Fixed by v0.9.2
